### ISSUE TITLE
Make btree_gin optional

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datastore#225]
When running tests locally the test database test user isn't normally going to have super user privileges resulting in:

```
$ ./datastore/manage.py test tests.test_commands
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied to create extension "btree_gin"
HINT:  Must be superuser to create this extension.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./datastore/manage.py", line 21, in <module>
    main()
  File "./datastore/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/commands/test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/test/runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/test/runner.py", line 643, in setup_databases
    return _setup_databases(
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/test/utils.py", line 179, in setup_databases
    connection.creation.create_test_db(
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/base/creation.py", line 74, in create_test_db
    call_command(
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/contrib/postgres/operations.py", line 25, in database_forwards
    schema_editor.execute(
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/michael/dev/ods/threesixtygiving/datastore/.ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied to create extension "btree_gin"

```

Can we make this optional in the migrations?

**Comment by michaelwood** [comment]
Any thoughts on this @R2ZER0 ?

**Comment by R2ZER0** [comment]
I agree it's quite annoying, I think extensions handling/permissions is one of the unsolved oddities of Postgres and Django Migrations since (without mods) only superusers can install extensions.

The migration in question is https://github.com/ThreeSixtyGiving/datastore/blob/live/datastore/db/migrations/0023_auto_20240318_1952.py
which installs the extension, and then creates the indexes that use it. Indexes being optional, I guess in theory we could make this migration optional.

One way to do this, it looks like we could edit the migration to override `__init__`, and conditionally set `operations = []` to effectively disable the migration based on some Django setting or environment variable.
Alternatively convert the migration to a custom RunPython / RunSQL.

**Comment by R2ZER0** [comment]
Then we could add a setting say, `ENABLE_INDEXES_REQUIRING_EXTENSIONS = False` to the settings file used by the tests?
