### ISSUE TITLE
Errors loading FTC school organisation types

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datastore#73]
bash ./additional_data/sources/load_all_org_data.sh :

```Guessed org_type schools_gias
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/michael/datastore/datastore/additional_data/management/commands/load_org_data.py", line 33, in handle
    options["path"], org_type=options.get("org_type")
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 111, in import_from_path
    added = self.process_csv(file_data, org_type)
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 82, in process_csv
    data=row, org_type=org_type, org_id=row["id"], org_ids=row["orgIDs"]
KeyError: 'id'
Guessed org_type schools_ni
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/michael/datastore/datastore/additional_data/management/commands/load_org_data.py", line 33, in handle
    options["path"], org_type=options.get("org_type")
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 111, in import_from_path
    added = self.process_csv(file_data, org_type)
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 82, in process_csv
    data=row, org_type=org_type, org_id=row["id"], org_ids=row["orgIDs"]
KeyError: 'id'
Guessed org_type schools_scotland
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/michael/datastore/datastore/additional_data/management/commands/load_org_data.py", line 33, in handle
    options["path"], org_type=options.get("org_type")
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 111, in import_from_path
    added = self.process_csv(file_data, org_type)
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 82, in process_csv
    data=row, org_type=org_type, org_id=row["id"], org_ids=row["orgIDs"]
KeyError: 'id'
Guessed org_type schools_wales
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michael/datastore/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/michael/datastore/datastore/additional_data/management/commands/load_org_data.py", line 33, in handle
    options["path"], org_type=options.get("org_type")
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 111, in import_from_path
    added = self.process_csv(file_data, org_type)
  File "/home/michael/datastore/datastore/additional_data/sources/find_that_charity.py", line 82, in process_csv
    data=row, org_type=org_type, org_id=row["id"], org_ids=row["orgIDs"]
KeyError: 'id'
```

**Comment by michaelwood** [comment]
@drkane hmm looks like the data for schools is 404ing at the moment. e.g. https://findthatcharity.uk/orgid/source/schools_gias.csv

**Comment by drkane** [comment]
@michaelwood - thanks, I'll take a look

**Comment by drkane** [comment]
Ah - I've got the source IDs wrong. Correct ones should be:

```
./manage.py load_org_data https://findthatcharity.uk/orgid/source/gias.csv
./manage.py load_org_data https://findthatcharity.uk/orgid/source/nideptofeducation.csv
./manage.py load_org_data https://findthatcharity.uk/orgid/source/schoolsscotland.csv
./manage.py load_org_data https://findthatcharity.uk/orgid/source/walesschools.csv
```

I'll do a PR

**Comment by michaelwood** [comment]
Just remembered we will also need to specify the org type as the mapping in https://github.com/ThreeSixtyGiving/datastore/blob/master/datastore/additional_data/models.py#L27 will now no longer auto detect the org type correctly. When it loads via: https://github.com/ThreeSixtyGiving/datastore/blob/master/datastore/additional_data/sources/find_that_charity.py#L97

I can specify manually on the command line i.e. ```
./manage.py load_org_data https://findthatcharity.uk/orgid/source/gias.csv schools_gias
./manage.py load_org_data https://findthatcharity.uk/orgid/source/nideptofeducation.csv schools_ni
./manage.py load_org_data https://findthatcharity.uk/orgid/source/schoolsscotland.csv schools_scotland
./manage.py load_org_data https://findthatcharity.uk/orgid/source/walesschools.csv schools_wales
```

Not sure if that is what we want to do permanently?

**Comment by drkane** [comment]
I don't think there's anywhere else that uses those orgtypes so they could probably be changed without causing any issues - might be better in the long run to do that rather than change it in the bash file.

**Comment by michaelwood** [comment]
> I don't think there's anywhere else that uses those orgtypes so they could probably be changed without causing any issues - might be better in the long run to do that rather than change it in the bash file.

Yeah, agreed, the fewer manual mappings the better.

**Comment by michaelwood** [comment]
I think this is closed, the datastore now has the type id mappings set (rather than guessing), so whatever the filename is set to in the future won't matter.
